'use client'
import Navbar from './components/Navbar';
import './globals.css';
import { Providers } from './providers';
import { AuthContextProvider } from './context/AuthContext';

export const metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AuthContextProvider>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </AuthContextProvider>
      </body>
    </html>
  )
}
